[package]
name = "workflow-schema"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
url.workspace = true
workflow-actions = { path = "../workflow-actions" }
workflow-core = { path = "../workflow-core" }
workflow-expression = { path = "../workflow-expression" }

[dev-dependencies]
